{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "bf25d867-cc8e-4533-9ddb-fd53052f79e0",
   "metadata": {},
   "source": [
    "\n",
    "<h1>PHASE 1 — Enhanced Data Simulation</h1>\n",
    "<h2>Insurance Portfolio Intelligence Suite</h2>\n",
    "\n",
    "WHAT WE ADDED VS ORIGINAL:\n",
    "- Customer Age (affects risk profile)\n",
    "- City Tier (1 = metro, 2 = mid-size, 3 = small town)\n",
    "- Vehicle Category (Hatchback, Sedan, SUV, Luxury)\n",
    "- Risk-based Premium (not just tenure * 100)\n",
    "- Variable Claim Amounts (log-normal distribution, not fixed 10000)\n",
    "- Fraud Flags (2% of claims marked suspicious)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c0ffab07-6dca-4be2-ad0b-aaada6cbcf43",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Policy dataset created\n",
      "   Shape: (1000000, 11)\n",
      "   Total Premium: ₹2,929,306,462\n",
      "\n",
      "   Vehicle Category Distribution:\n",
      "Vehicle_Category\n",
      "Hatchback    349565\n",
      "Sedan        300009\n",
      "SUV          250451\n",
      "Luxury        99975\n",
      "Name: count, dtype: int64\n",
      "\n",
      "   City Tier Distribution:\n",
      "City_Tier\n",
      "1    400599\n",
      "2    349918\n",
      "3    249483\n",
      "Name: count, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    " \n",
    "# Fix random seed so results are reproducible every time you run\n",
    "np.random.seed(42)\n",
    " \n",
    "# ─────────────────────────────────────────\n",
    "# STEP 1 — POLICY / CUSTOMER DATA\n",
    "# ─────────────────────────────────────────\n",
    " \n",
    "n = 1_000_000  # 1 million customers\n",
    " \n",
    "# Purchase dates spread evenly across 2024\n",
    "dates = pd.date_range(\"2024-01-01\", \"2024-12-31\")\n",
    " \n",
    "df = pd.DataFrame({\n",
    "    \"Customer_ID\": range(1, n + 1),\n",
    "    \"Vehicle_ID\":  range(1, n + 1),\n",
    "    \"Policy_Purchase_Date\": np.random.choice(dates, n)\n",
    "})\n",
    " \n",
    "# --- Customer Age ---\n",
    "# Real insurance customers range from 18 to 70\n",
    "# Younger and older drivers are statistically riskier\n",
    "df[\"Customer_Age\"] = np.random.randint(18, 71, n)\n",
    " \n",
    "# --- City Tier ---\n",
    "# Tier 1 = Metro (Mumbai, Delhi) — higher claim frequency, higher premium\n",
    "# Tier 2 = Mid-size cities — moderate\n",
    "# Tier 3 = Small towns — lower frequency\n",
    "df[\"City_Tier\"] = np.random.choice([1, 2, 3], n, p=[0.40, 0.35, 0.25])\n",
    " \n",
    "# --- Vehicle Category ---\n",
    "# Luxury cars cost more to repair → higher claims\n",
    "df[\"Vehicle_Category\"] = np.random.choice(\n",
    "    [\"Hatchback\", \"Sedan\", \"SUV\", \"Luxury\"],\n",
    "    n,\n",
    "    p=[0.35, 0.30, 0.25, 0.10]\n",
    ")\n",
    " \n",
    "# --- Vehicle Value (based on category, not fixed) ---\n",
    "vehicle_value_map = {\n",
    "    \"Hatchback\": 500_000,\n",
    "    \"Sedan\":     800_000,\n",
    "    \"SUV\":     1_200_000,\n",
    "    \"Luxury\":  2_500_000\n",
    "}\n",
    "df[\"Vehicle_Value\"] = df[\"Vehicle_Category\"].map(vehicle_value_map)\n",
    " \n",
    "# --- Policy Tenure ---\n",
    "tenures = [1, 2, 3, 4]\n",
    "probs   = [0.20, 0.30, 0.40, 0.10]\n",
    "df[\"Policy_Tenure\"] = np.random.choice(tenures, n, p=probs)\n",
    " \n",
    "# --- Risk-Based Premium ---\n",
    "# Base = Tenure * 1000 (increased from 100 to be realistic)\n",
    "# Age surcharge: young (<25) and senior (>60) pay 20% more\n",
    "# City surcharge: Tier 1 = +15%, Tier 2 = +5%, Tier 3 = 0%\n",
    "# Vehicle surcharge: SUV +10%, Luxury +25%\n",
    " \n",
    "base_premium = df[\"Policy_Tenure\"] * 1000\n",
    " \n",
    "age_factor = np.where(\n",
    "    (df[\"Customer_Age\"] < 25) | (df[\"Customer_Age\"] > 60), 1.20, 1.00\n",
    ")\n",
    " \n",
    "city_factor = df[\"City_Tier\"].map({1: 1.15, 2: 1.05, 3: 1.00})\n",
    " \n",
    "vehicle_factor = df[\"Vehicle_Category\"].map({\n",
    "    \"Hatchback\": 1.00,\n",
    "    \"Sedan\":     1.05,\n",
    "    \"SUV\":       1.10,\n",
    "    \"Luxury\":    1.25\n",
    "})\n",
    " \n",
    "df[\"Premium\"] = (base_premium * age_factor * city_factor * vehicle_factor).round(2)\n",
    " \n",
    "# --- Policy Dates ---\n",
    "df[\"Policy_Start_Date\"] = df[\"Policy_Purchase_Date\"] + pd.Timedelta(days=365)\n",
    "df[\"Policy_End_Date\"]   = df[\"Policy_Start_Date\"] + pd.to_timedelta(\n",
    "    df[\"Policy_Tenure\"] * 365, unit=\"D\"\n",
    ")\n",
    " \n",
    "print(\"✅ Policy dataset created\")\n",
    "print(f\"   Shape: {df.shape}\")\n",
    "print(f\"   Total Premium: ₹{df['Premium'].sum():,.0f}\")\n",
    "print(f\"\\n   Vehicle Category Distribution:\")\n",
    "print(df[\"Vehicle_Category\"].value_counts())\n",
    "print(f\"\\n   City Tier Distribution:\")\n",
    "print(df[\"City_Tier\"].value_counts())\n",
    " "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2b3aa939-6cfd-482e-a8a1-63732bd1bc24",
   "metadata": {},
   "source": [
    "\n",
    "# STEP 2 — CLAIMS 2025\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "51ca3c72-57fb-4ed3-8d15-f5279acb60ad",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "✅ Claims 2025 created\n",
      "   Total Claims: 39,397\n",
      "   Total Claim Amount: ₹4,392,452,052\n",
      "   Avg Claim Amount: ₹111,492\n",
      "   Fraud Flags: 776\n"
     ]
    }
   ],
   "source": [
    "# Same logic as original: only vehicles bought on 7,14,21,28 of each month\n",
    "df[\"purchase_day\"] = df[\"Policy_Purchase_Date\"].dt.day\n",
    "eligible_2025 = df[df[\"purchase_day\"].isin([7, 14, 21, 28])]\n",
    " \n",
    "# 30% of eligible vehicles file a claim\n",
    "claims_2025 = eligible_2025.sample(frac=0.30, random_state=42).copy()\n",
    " \n",
    "# --- Variable Claim Amounts (KEY UPGRADE) ---\n",
    "# Original used fixed ₹10,000\n",
    "# Now we use log-normal distribution centered around 10% of vehicle value\n",
    "# Log-normal is the standard distribution used in insurance actuarial work\n",
    "# It produces mostly moderate claims with occasional large ones — realistic\n",
    " \n",
    "claim_mean   = claims_2025[\"Vehicle_Value\"] * 0.10   # mean = 10% of vehicle value\n",
    "claim_std    = claim_mean * 0.40                      # std = 40% of mean\n",
    " \n",
    "# Log-normal parameters (mu, sigma in log space)\n",
    "mu    = np.log(claim_mean**2 / np.sqrt(claim_std**2 + claim_mean**2))\n",
    "sigma = np.sqrt(np.log(1 + (claim_std / claim_mean)**2))\n",
    " \n",
    "claims_2025[\"Claim_Amount\"] = np.random.lognormal(mu, sigma).round(2)\n",
    "claims_2025[\"Claim_Amount\"] = claims_2025[\"Claim_Amount\"].clip(\n",
    "    lower=1000, upper=claims_2025[\"Vehicle_Value\"]\n",
    ").round(2)\n",
    " \n",
    "claims_2025[\"Claim_Date\"] = claims_2025[\"Policy_Start_Date\"]\n",
    "claims_2025[\"Claim_Type\"] = 1\n",
    " \n",
    "# --- Fraud Flags ---\n",
    "# ~2% of claims are flagged as potentially fraudulent\n",
    "# Fraud detection is a hot topic in insurance analytics\n",
    "fraud_mask = np.random.random(len(claims_2025)) < 0.02\n",
    "claims_2025[\"Is_Fraud_Flag\"] = fraud_mask.astype(int)\n",
    " \n",
    "# Fraudulent claims tend to be suspiciously high — bump them up\n",
    "claims_2025.loc[claims_2025[\"Is_Fraud_Flag\"] == 1, \"Claim_Amount\"] = (\n",
    "    claims_2025.loc[claims_2025[\"Is_Fraud_Flag\"] == 1, \"Vehicle_Value\"] * 0.90\n",
    ")\n",
    " \n",
    "claims_2025 = claims_2025[[\n",
    "    \"Customer_ID\", \"Vehicle_ID\", \"Claim_Amount\",\n",
    "    \"Claim_Date\", \"Claim_Type\", \"Is_Fraud_Flag\"\n",
    "]].copy()\n",
    " \n",
    "claims_2025[\"Claim_ID\"] = range(1, len(claims_2025) + 1)\n",
    "claims_2025 = claims_2025[[\n",
    "    \"Claim_ID\", \"Customer_ID\", \"Vehicle_ID\",\n",
    "    \"Claim_Amount\", \"Claim_Date\", \"Claim_Type\", \"Is_Fraud_Flag\"\n",
    "]]\n",
    "claims_2025 = claims_2025.reset_index(drop=True)\n",
    " \n",
    "print(f\"\\n✅ Claims 2025 created\")\n",
    "print(f\"   Total Claims: {len(claims_2025):,}\")\n",
    "print(f\"   Total Claim Amount: ₹{claims_2025['Claim_Amount'].sum():,.0f}\")\n",
    "print(f\"   Avg Claim Amount: ₹{claims_2025['Claim_Amount'].mean():,.0f}\")\n",
    "print(f\"   Fraud Flags: {claims_2025['Is_Fraud_Flag'].sum():,}\")\n",
    " \n",
    " \n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "19964991-b672-403c-beba-429d46687a4b",
   "metadata": {},
   "source": [
    "\n",
    "# STEP 3 — CLAIMS 2026 (Jan–Feb)\n",
    "\n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e56d6e0d-096d-4099-add0-e60360a1df5b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "✅ Claims 2026 created\n",
      "   Total Claims: 9,970\n",
      "   Total Claim Amount: ₹1,104,825,090\n"
     ]
    }
   ],
   "source": [
    "tenure4      = df[df[\"Policy_Tenure\"] == 4].copy()\n",
    "claims_2026  = tenure4.sample(frac=0.10, random_state=42).copy()\n",
    " \n",
    "claim_dates  = pd.date_range(\"2026-01-01\", \"2026-02-28\")\n",
    "claims_2026[\"Claim_Date\"] = np.random.choice(claim_dates, len(claims_2026))\n",
    " \n",
    "claim_mean2  = claims_2026[\"Vehicle_Value\"] * 0.10\n",
    "claim_std2   = claim_mean2 * 0.40\n",
    " \n",
    "mu2    = np.log(claim_mean2**2 / np.sqrt(claim_std2**2 + claim_mean2**2))\n",
    "sigma2 = np.sqrt(np.log(1 + (claim_std2 / claim_mean2)**2))\n",
    " \n",
    "claims_2026[\"Claim_Amount\"] = np.random.lognormal(mu2, sigma2).round(2)\n",
    "claims_2026[\"Claim_Amount\"] = claims_2026[\"Claim_Amount\"].clip(\n",
    "    lower=1000, upper=claims_2026[\"Vehicle_Value\"]\n",
    ").round(2)\n",
    " \n",
    "claims_2026[\"Claim_Type\"]    = 2\n",
    " \n",
    "fraud_mask2 = np.random.random(len(claims_2026)) < 0.02\n",
    "claims_2026[\"Is_Fraud_Flag\"] = fraud_mask2.astype(int)\n",
    " \n",
    "claims_2026.loc[claims_2026[\"Is_Fraud_Flag\"] == 1, \"Claim_Amount\"] = (\n",
    "    claims_2026.loc[claims_2026[\"Is_Fraud_Flag\"] == 1, \"Vehicle_Value\"] * 0.90\n",
    ")\n",
    " \n",
    "claims_2026 = claims_2026[[\n",
    "    \"Customer_ID\", \"Vehicle_ID\", \"Claim_Amount\",\n",
    "    \"Claim_Date\", \"Claim_Type\", \"Is_Fraud_Flag\"\n",
    "]].copy()\n",
    " \n",
    "claims_2026[\"Claim_ID\"] = range(\n",
    "    len(claims_2025) + 1,\n",
    "    len(claims_2025) + len(claims_2026) + 1\n",
    ")\n",
    "claims_2026 = claims_2026[[\n",
    "    \"Claim_ID\", \"Customer_ID\", \"Vehicle_ID\",\n",
    "    \"Claim_Amount\", \"Claim_Date\", \"Claim_Type\", \"Is_Fraud_Flag\"\n",
    "]]\n",
    "claims_2026 = claims_2026.reset_index(drop=True)\n",
    " \n",
    "print(f\"\\n✅ Claims 2026 created\")\n",
    "print(f\"   Total Claims: {len(claims_2026):,}\")\n",
    "print(f\"   Total Claim Amount: ₹{claims_2026['Claim_Amount'].sum():,.0f}\")\n",
    " "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "efd3b9d1-f63b-43e4-bc75-0bd4c0e610e4",
   "metadata": {},
   "source": [
    "\n",
    "# STEP 4 — COMBINE & EXPORT\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "5e0c683f-ea75-47c2-b743-49654df45233",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "✅ Files exported:\n",
      "   policy_enhanced.csv — 1,000,000 rows\n",
      "   claims_enhanced.csv — 49,367 rows\n",
      "\n",
      "📊 FINAL SUMMARY\n",
      "   Total Premium Collected : ₹       2,929,306,462\n",
      "   Total Claims Filed      :               49,367\n",
      "   Total Claim Amount      : ₹       5,497,277,142\n",
      "   Portfolio Loss Ratio    :              187.66%\n",
      "   Fraud Flags             :                  967\n"
     ]
    }
   ],
   "source": [
    "claims = pd.concat([claims_2025, claims_2026]).reset_index(drop=True)\n",
    " \n",
    "# Export policy with all new fields\n",
    "policy_cols = [\n",
    "    \"Customer_ID\", \"Vehicle_ID\", \"Customer_Age\", \"City_Tier\",\n",
    "    \"Vehicle_Category\", \"Vehicle_Value\", \"Policy_Tenure\",\n",
    "    \"Premium\", \"Policy_Purchase_Date\", \"Policy_Start_Date\", \"Policy_End_Date\"\n",
    "]\n",
    "df[policy_cols].to_csv(\"policy_enhanced.csv\", index=False)\n",
    "claims.to_csv(\"claims_enhanced.csv\", index=False)\n",
    " \n",
    "print(f\"\\n✅ Files exported:\")\n",
    "print(f\"   policy_enhanced.csv — {len(df):,} rows\")\n",
    "print(f\"   claims_enhanced.csv — {len(claims):,} rows\")\n",
    "print(f\"\\n📊 FINAL SUMMARY\")\n",
    "print(f\"   Total Premium Collected : ₹{df['Premium'].sum():>20,.0f}\")\n",
    "print(f\"   Total Claims Filed      : {len(claims):>20,}\")\n",
    "print(f\"   Total Claim Amount      : ₹{claims['Claim_Amount'].sum():>20,.0f}\")\n",
    "print(f\"   Portfolio Loss Ratio    : {claims['Claim_Amount'].sum() / df['Premium'].sum():>20.2%}\")\n",
    "print(f\"   Fraud Flags             : {claims['Is_Fraud_Flag'].sum():>20,}\")\n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca3bce9d-3b30-4806-bb80-7ab9ce7531ad",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
